package utils

import (
	"errors"
)

// GetCountryCode converts a full country name and returns a country code
func GetCountryCode(country string) (string, error) {
	countryMap := map[string]string{
		"Afghanistan":                         "AF",
		"Aland Islands":                       "AX",
		"Albania":                             "AL",
		"Algeria":                             "DZ",
		"American Samoa":                      "AS",
		"Andorra":                             "AD",
		"Angola":                              "AO",
		"Anguilla":                            "AI",
		"Antarctica":                          "AQ",
		"Antigua and Barbuda":                 "AG",
		"Argentina":                           "AR",
		"Armenia":                             "AM",
		"Aruba":                               "AW",
		"Australia":                           "AU",
		"Austria":                             "AT",
		"Azerbaijan":                          "AZ",
		"Bahamas":                             "BS",
		"Bahrain":                             "BH",
		"Bangladesh":                          "BD",
		"Barbados":                            "BB",
		"Belarus":                             "BY",
		"Belgium":                             "BE",
		"Belize":                              "BZ",
		"Benin":                               "BJ",
		"Bermuda":                             "BM",
		"Bhutan":                              "BT",
		"Bolivia":                             "BO",
		"Bonaire":                             "BQ",
		"Bosnia and Herzegovina":              "BA",
		"Botswana":                            "BW",
		"Bouvet Island":                       "BV",
		"Brazil":                              "BR",
		"British Indian Ocean Territory":      "IO",
		"Brunei":                              "BN",
		"Bulgaria":                            "BG",
		"Burkina Faso":                        "BF",
		"Burundi":                             "BI",
		"Cape Verde":                          "CV",
		"Cambodia":                            "KH",
		"Cameroon":                            "CM",
		"Canada":                              "CA",
		"Cayman Islands":                      "KY",
		"Central African Republic":            "CF",
		"Chad":                                "TD",
		"Chile":                               "CL",
		"China":                               "CN",
		"Christmas Island":                    "CX",
		"Cocos Islands":                       "CC",
		"Colombia":                            "CO",
		"Comoros":                             "KM",
		"Democratic Republic of the Congo":    "CD",
		"Republic of the Congo":               "CG",
		"Cook Islands":                        "CK",
		"Costa Rica":                          "CR",
		"Ivory Coast":                         "CI",
		"Croatia":                             "HR",
		"Cuba":                                "CU",
		"Curaçao":                             "CW",
		"Cyprus":                              "CY",
		"Czech Republic":                      "CZ",
		"Denmark":                             "DK",
		"Djibouti":                            "DJ",
		"Dominica":                            "DM",
		"Dominican Republic":                  "DO",
		"Ecuador":                             "EC",
		"Egypt":                               "EG",
		"El Salvador":                         "SV",
		"Equatorial Guinea":                   "GQ",
		"Eritrea":                             "ER",
		"Estonia":                             "EE",
		"Eswatini":                            "SZ",
		"Ethiopia":                            "ET",
		"Falkland Islands":                    "FK",
		"Faroe Islands":                       "FO",
		"Fiji":                                "FJ",
		"Finland":                             "FI",
		"France":                              "FR",
		"French Guiana":                       "GF",
		"French Polynesia":                    "PF",
		"French Southern and Antarctic Lands": "TF",
		"Gabon":                               "GA",
		"The Gambia":                          "GM",
		"Georgia":                             "GE",
		"Germany":                             "DE",
		"Ghana":                               "GH",
		"Gibraltar":                           "GI",
		"Greece":                              "GR",
		"Greenland":                           "GL",
		"Grenada":                             "GD",
		"Guadeloupe":                          "GP",
		"Guam":                                "GU",
		"Guatemala":                           "GT",
		"Bailiwick of Guernsey":               "GG",
		"Guinea":                              "GN",
		"Guinea-Bissau":                       "GW",
		"Guyana":                              "GY",
		"Haiti":                               "HT",
		"Heard Island and McDonald Islands":   "HM",
		"Holy See":                            "VA",
		"Honduras":                            "HN",
		"Hong Kong":                           "HK",
		"Hungary":                             "HU",
		"Iceland":                             "IS",
		"India":                               "IN",
		"Indonesia":                           "ID",
		"Iran":                                "IR",
		"Iraq":                                "IQ",
		"Republic of Ireland":                 "IE",
		"Isle of Man":                         "IM",
		"Israel":                              "IL",
		"Italy":                               "IT",
		"Jamaica":                             "JM",
		"Japan":                               "JP",
		"Jersey":                              "JE",
		"Jordan":                              "JO",
		"Kazakhstan":                          "KZ",
		"Kenya":                               "KE",
		"Kiribati":                            "KI",
		"North Korea":                         "KP",
		"South Korea":                         "KR",
		"Kuwait":                              "KW",
		"Kyrgyzstan":                          "KG",
		"Laos":                                "LA",
		"Latvia":                              "LV",
		"Lebanon":                             "LB",
		"Lesotho":                             "LS",
		"Liberia":                             "LR",
		"Libya":                               "LY",
		"Liechtenstein":                       "LI",
		"Lithuania":                           "LT",
		"Luxembourg":                          "LU",
		"Macau":                               "MO",
		"North Macedonia":                     "MK",
		"Madagascar":                          "MG",
		"Malawi":                              "MW",
		"Malaysia":                            "MY",
		"Maldives":                            "MV",
		"Mali":                                "ML",
		"Malta":                               "MT",
		"Marshall Islands":                    "MH",
		"Martinique":                          "MQ",
		"Mauritania":                          "MR",
		"Mauritius":                           "MU",
		"Mayotte":                             "YT",
		"Mexico":                              "MX",
		"Federated States of Micronesia":      "FM",
		"Moldova":                             "MD",
		"Monaco":                              "MC",
		"Mongolia":                            "MN",
		"Montenegro":                          "ME",
		"Montserrat":                          "MS",
		"Morocco":                             "MA",
		"Mozambique":                          "MZ",
		"Myanmar":                             "MM",
		"Namibia":                             "NA",
		"Nauru":                               "NR",
		"Nepal":                               "NP",
		"Netherlands":                         "NL",
		"New Caledonia":                       "NC",
		"New Zealand":                         "NZ",
		"Nicaragua":                           "NI",
		"Niger":                               "NE",
		"Nigeria":                             "NG",
		"Niue":                                "NU",
		"Norfolk Island":                      "NF",
		"Northern Mariana Islands":            "MP",
		"Norway":                              "NO",
		"Oman":                                "OM",
		"Pakistan":                            "PK",
		"Palau":                               "PW",
		"State of Palestine":                  "PS",
		"Panama":                              "PA",
		"Papua New Guinea":                    "PG",
		"Paraguay":                            "PY",
		"Peru":                                "PE",
		"Philippines":                         "PH",
		"Pitcairn Islands":                    "PN",
		"Poland":                              "PL",
		"Portugal":                            "PT",
		"Puerto Rico":                         "PR",
		"Qatar":                               "QA",
		"Réunion":                             "RE",
		"Romania":                             "RO",
		"Russia":                              "RU",
		"Rwanda":                              "RW",
		"Saint Barthélemy":                    "BL",
		"Saint Helena":                        "SH",
		"Saint Kitts and Nevis":               "KN",
		"Saint Lucia":                         "LC",
		"Collectivity of Saint Martin":        "MF",
		"Saint Pierre and Miquelon":           "PM",
		"Saint Vincent and the Grenadines":    "VC",
		"Samoa":                               "WS",
		"San Marino":                          "SM",
		"São Tomé and Príncipe":               "ST",
		"Saudi Arabia":                        "SA",
		"Senegal":                             "SN",
		"Serbia":                              "RS",
		"Seychelles":                          "SC",
		"Sierra Leone":                        "SL",
		"Singapore":                           "SG",
		"Sint Maarten":                        "SX",
		"Slovakia":                            "SK",
		"Slovenia":                            "SI",
		"Solomon Islands":                     "SB",
		"Somalia":                             "SO",
		"South Africa":                        "ZA",
		"South Georgia and the South Sandwich Islands": "GS",
		"South Sudan":                  "SS",
		"Spain":                        "ES",
		"Sri Lanka":                    "LK",
		"Sudan":                        "SD",
		"Suriname":                     "SR",
		"Svalbard":                     "SJ",
		"Sweden":                       "SE",
		"Switzerland":                  "CH",
		"Syria":                        "SY",
		"Taiwan":                       "TW",
		"Tajikistan":                   "TJ",
		"Tanzania":                     "TZ",
		"Thailand":                     "TH",
		"East Timor":                   "TL",
		"Togo":                         "TG",
		"Tokelau":                      "TK",
		"Tonga":                        "TO",
		"Trinidad and Tobago":          "TT",
		"Tunisia":                      "TN",
		"Turkey":                       "TR",
		"Turkmenistan":                 "TM",
		"Turks and Caicos Islands":     "TC",
		"Tuvalu":                       "TV",
		"Uganda":                       "UG",
		"Ukraine":                      "UA",
		"United Arab Emirates":         "AE",
		"United Kingdom":               "GB",
		"United States":                "US",
		"Uruguay":                      "UY",
		"Uzbekistan":                   "UZ",
		"Vanuatu":                      "VU",
		"Venezuela":                    "VE",
		"Vietnam":                      "VN",
		"British Virgin Islands":       "VG",
		"United States Virgin Islands": "VI",
		"Wallis and Futuna":            "WF",
		"Western Sahara":               "EH",
		"Yemen":                        "YE",
		"Zambia":                       "ZM",
		"Zimbabwe":                     "ZW",
	}

	if code, ok := countryMap[country]; ok {
		return code, nil
	}

	return "", errors.New("failed to get country code for " + country)
}

// GetCountryName converts a country code and returns a full country name
func GetCountryName(countryCode string) (string, error) {
	countryMap := map[string]string{
		"AF":                    "Afghanistan",
		"AX":                    "Aland Islands",
		"AL":                    "Albania",
		"DZ":                    "Algeria",
		"AS":                    "American Samoa",
		"AD":                    "Andorra",
		"AO":                    "Angola",
		"AI":                    "Anguilla",
		"AQ":                    "Antarctica",
		"AG":                    "Antigua and Barbuda",
		"AR":                    "Argentina",
		"AM":                    "Armenia",
		"AW":                    "Aruba",
		"AU":                    "Australia",
		"AT":                    "Austria",
		"AZ":                    "Azerbaijan",
		"BS":                    "Bahamas",
		"BH":                    "Bahrain",
		"BD":                    "Bangladesh",
		"BB":                    "Barbados",
		"BY":                    "Belarus",
		"BE":                    "Belgium",
		"BZ":                    "Belize",
		"BJ":                    "Benin",
		"BM":                    "Bermuda",
		"BT":                    "Bhutan",
		"BO":                    "Bolivia",
		"BQ":                    "Bonaire",
		"BA":                    "Bosnia and Herzegovina",
		"BW":                    "Botswana",
		"BV":                    "Bouvet Island",
		"BR":                    "Brazil",
		"IO":                    "British Indian Ocean Territory",
		"BN":                    "Brunei",
		"BG":                    "Bulgaria",
		"BF":                    "Burkina Faso",
		"BI":                    "Burundi",
		"CV":                    "Cape Verde",
		"KH":                    "Cambodia",
		"CM":                    "Cameroon",
		"CA":                    "Canada",
		"KY":                    "Cayman Islands",
		"CF":                    "Central African Republic",
		"TD":                    "Chad",
		"CL":                    "Chile",
		"CN":                    "China",
		"CX":                    "Christmas Island",
		"CC":                    "Cocos Islands",
		"CO":                    "Colombia",
		"KM":                    "Comoros",
		"CD":                    "Democratic Republic of the Congo",
		"CG":                    "Republic of the Congo",
		"CK":                    "Cook Islands",
		"CR":                    "Costa Rica",
		"CI":                    "Ivory Coast",
		"HR":                    "Croatia",
		"CU":                    "Cuba",
		"Curaçao":               "CW",
		"CY":                    "Cyprus",
		"CZ":                    "Czech Republic",
		"DK":                    "Denmark",
		"DJ":                    "Djibouti",
		"DM":                    "Dominica",
		"DO":                    "Dominican Republic",
		"EC":                    "Ecuador",
		"EG":                    "Egypt",
		"SV":                    "El Salvador",
		"GQ":                    "Equatorial Guinea",
		"ER":                    "Eritrea",
		"EE":                    "Estonia",
		"SZ":                    "Eswatini",
		"ET":                    "Ethiopia",
		"FK":                    "Falkland Islands",
		"FO":                    "Faroe Islands",
		"FJ":                    "Fiji",
		"FI":                    "Finland",
		"FR":                    "France",
		"GF":                    "French Guiana",
		"PF":                    "French Polynesia",
		"TF":                    "French Southern and Antarctic Lands",
		"GA":                    "Gabon",
		"GM":                    "The Gambia",
		"GE":                    "Georgia",
		"DE":                    "Germany",
		"GH":                    "Ghana",
		"GI":                    "Gibraltar",
		"GR":                    "Greece",
		"GL":                    "Greenland",
		"GD":                    "Grenada",
		"GP":                    "Guadeloupe",
		"GU":                    "Guam",
		"GT":                    "Guatemala",
		"GG":                    "Bailiwick of Guernsey",
		"GN":                    "Guinea",
		"Guinea-Bissau":         "GW",
		"GY":                    "Guyana",
		"HT":                    "Haiti",
		"HM":                    "Heard Island and McDonald Islands",
		"VA":                    "Holy See",
		"HN":                    "Honduras",
		"HK":                    "Hong Kong",
		"HU":                    "Hungary",
		"IS":                    "Iceland",
		"IN":                    "India",
		"ID":                    "Indonesia",
		"IR":                    "Iran",
		"IQ":                    "Iraq",
		"IE":                    "Republic of Ireland",
		"IM":                    "Isle of Man",
		"IL":                    "Israel",
		"IT":                    "Italy",
		"JM":                    "Jamaica",
		"JP":                    "Japan",
		"JE":                    "Jersey",
		"JO":                    "Jordan",
		"KZ":                    "Kazakhstan",
		"KE":                    "Kenya",
		"KI":                    "Kiribati",
		"KP":                    "North Korea",
		"KR":                    "South Korea",
		"KW":                    "Kuwait",
		"KG":                    "Kyrgyzstan",
		"LA":                    "Laos",
		"LV":                    "Latvia",
		"LB":                    "Lebanon",
		"LS":                    "Lesotho",
		"LR":                    "Liberia",
		"LY":                    "Libya",
		"LI":                    "Liechtenstein",
		"LT":                    "Lithuania",
		"LU":                    "Luxembourg",
		"MO":                    "Macau",
		"MK":                    "North Macedonia",
		"MG":                    "Madagascar",
		"MW":                    "Malawi",
		"MY":                    "Malaysia",
		"MV":                    "Maldives",
		"ML":                    "Mali",
		"MT":                    "Malta",
		"MH":                    "Marshall Islands",
		"MQ":                    "Martinique",
		"MR":                    "Mauritania",
		"MU":                    "Mauritius",
		"YT":                    "Mayotte",
		"MX":                    "Mexico",
		"FM":                    "Federated States of Micronesia",
		"MD":                    "Moldova",
		"MC":                    "Monaco",
		"MN":                    "Mongolia",
		"ME":                    "Montenegro",
		"MS":                    "Montserrat",
		"MA":                    "Morocco",
		"MZ":                    "Mozambique",
		"MM":                    "Myanmar",
		"NA":                    "Namibia",
		"NR":                    "Nauru",
		"NP":                    "Nepal",
		"NL":                    "Netherlands",
		"NC":                    "New Caledonia",
		"NZ":                    "New Zealand",
		"NI":                    "Nicaragua",
		"NE":                    "Niger",
		"NG":                    "Nigeria",
		"NU":                    "Niue",
		"NF":                    "Norfolk Island",
		"MP":                    "Northern Mariana Islands",
		"NO":                    "Norway",
		"OM":                    "Oman",
		"PK":                    "Pakistan",
		"PW":                    "Palau",
		"PS":                    "State of Palestine",
		"PA":                    "Panama",
		"PG":                    "Papua New Guinea",
		"PY":                    "Paraguay",
		"PE":                    "Peru",
		"PH":                    "Philippines",
		"PN":                    "Pitcairn Islands",
		"PL":                    "Poland",
		"PT":                    "Portugal",
		"PR":                    "Puerto Rico",
		"QA":                    "Qatar",
		"Réunion":               "RE",
		"RO":                    "Romania",
		"RU":                    "Russia",
		"RW":                    "Rwanda",
		"Saint Barthélemy":      "BL",
		"SH":                    "Saint Helena",
		"KN":                    "Saint Kitts and Nevis",
		"LC":                    "Saint Lucia",
		"MF":                    "Collectivity of Saint Martin",
		"PM":                    "Saint Pierre and Miquelon",
		"VC":                    "Saint Vincent and the Grenadines",
		"WS":                    "Samoa",
		"SM":                    "San Marino",
		"São Tomé and Príncipe": "ST",
		"SA":                    "Saudi Arabia",
		"SN":                    "Senegal",
		"RS":                    "Serbia",
		"SC":                    "Seychelles",
		"SL":                    "Sierra Leone",
		"SG":                    "Singapore",
		"SX":                    "Sint Maarten",
		"SK":                    "Slovakia",
		"SI":                    "Slovenia",
		"SB":                    "Solomon Islands",
		"SO":                    "Somalia",
		"ZA":                    "South Africa",
		"GS":                    "South Georgia and the South Sandwich Islands",
		"SS":                    "South Sudan",
		"ES":                    "Spain",
		"LK":                    "Sri Lanka",
		"SD":                    "Sudan",
		"SR":                    "Suriname",
		"SJ":                    "Svalbard",
		"SE":                    "Sweden",
		"CH":                    "Switzerland",
		"SY":                    "Syria",
		"TW":                    "Taiwan",
		"TJ":                    "Tajikistan",
		"TZ":                    "Tanzania",
		"TH":                    "Thailand",
		"TL":                    "East Timor",
		"TG":                    "Togo",
		"TK":                    "Tokelau",
		"TO":                    "Tonga",
		"TT":                    "Trinidad and Tobago",
		"TN":                    "Tunisia",
		"TR":                    "Turkey",
		"TM":                    "Turkmenistan",
		"TC":                    "Turks and Caicos Islands",
		"TV":                    "Tuvalu",
		"UG":                    "Uganda",
		"UA":                    "Ukraine",
		"AE":                    "United Arab Emirates",
		"GB":                    "United Kingdom",
		"US":                    "United States",
		"UY":                    "Uruguay",
		"UZ":                    "Uzbekistan",
		"VU":                    "Vanuatu",
		"VE":                    "Venezuela",
		"VN":                    "Vietnam",
		"VG":                    "British Virgin Islands",
		"VI":                    "United States Virgin Islands",
		"WF":                    "Wallis and Futuna",
		"EH":                    "Western Sahara",
		"YE":                    "Yemen",
		"ZM":                    "Zambia",
		"ZW":                    "Zimbabwe",
	}

	if code, ok := countryMap[countryCode]; ok {
		return code, nil
	}

	return "", errors.New("failed to get country name for " + countryCode)
}
